name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG]: "
labels: ["bug"]
assignees: []

body: 
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible to help us resolve it quickly.

  - type: dropdown
    id: bug-area
    attributes:
      label: Bug Area
      description: Which area of the application is affected?
      options:
        - Video Playback
        - Event Tracking
        - Game Time/Clock
        - Data Save/Load
        - Data Export/Import
        - User Interface
        - Settings/Configuration
        - License Validation
        - Remote Server/WebSocket
        - Application Startup
        - Application Crash
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - Application crashes or data loss
        - High - Major feature broken
        - Medium - Feature works but with issues
        - Low - Minor inconvenience
    validations: 
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: When I try to.. ., the application... 
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes: 
      label: Steps to Reproduce
      description: Detailed steps to reproduce the bug
      placeholder: |
        1. Open the application
        2. Load a video file
        3. Click on '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead... 
    validations:
      required: true

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages
      description: Copy any error messages, stack traces, or console output
      render: shell
      placeholder: |
        Exception in thread "main" java.lang.NullPointerException
        at com.axyvon.videoanalysis... 
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Application Version
      description: What version of the application are you using?
      placeholder: "0.1-ALPHA"
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: Operating System
      description: What OS and version are you using?
      placeholder: "Windows 11 Pro 23H2"
    validations:
      required: true

  - type: input
    id: java-version
    attributes: 
      label: Java Version
      description: What Java version is installed?  (if known)
      placeholder: "Java 21.0.1"
    validations:
      required: false

  - type: textarea
    id: video-info
    attributes:
      label: Video File Information (if applicable)
      description: If the bug involves video playback, provide details about the video file
      placeholder: |
        - Format: MP4
        - Codec: H.264
        - Resolution: 1920x1080
        - Duration: 45 minutes
    validations:
      required: false

  - type: textarea
    id: config-file
    attributes:
      label: Configuration Details (if applicable)
      description: Any relevant configuration settings
      placeholder: Custom save location, special settings, etc.
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help explain the problem
      placeholder: Drag and drop images here
    validations:
      required: false

  - type: dropdown
    id: reproducibility
    attributes:
      label: Reproducibility
      description: How often does this bug occur?
      options:
        - Always - Every time
        - Often - Most of the time
        - Sometimes - Intermittent
        - Rarely - Only happened once or twice
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might help us resolve this bug
    validations:
      required: false

  - type: checkboxes
    id: acknowledgments
    attributes:
      label: Acknowledgments
      options: 
        - label: I have searched existing issues to confirm this bug hasn't been reported
          required: true
        - label: I have provided all the information requested above
          required: true
        - label: I have included the error log (required when possible)
          required: false
        - label: I have tried restarting the application
          required: false
