name: 🚀 Feature Request
description: Suggest a new feature for Axyvon Video Analysis Client
title: "[FEATURE]: "
labels: ["feature", "request"]
assignees: []

body: 
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!  Please fill out the information below. 

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area of the application does this feature relate to?
      options:
        - Video Playback & Controls
        - Event Tracking
        - Game Time Management
        - Data Management (Import/Export)
        - User Interface
        - Configuration & Settings
        - Remote Control/API
        - License Management
        - Reports & Analytics
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the scenario where this feature would be useful
      placeholder: As a coach, I want to...  so that I can...
    validations:
      required: true

  - type: textarea
    id: current-workaround
    attributes:
      label: Current Workaround
      description: How do you currently accomplish this task (if at all)?
      placeholder: Currently I have to...
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups about the feature request
      placeholder: |
        - Screenshots/mockups
        - References to similar features in other applications
        - Any other relevant information
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Acknowledgments
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: I understand this is a proprietary application and feature implementation is at the discretion of Axyvon
          required: true
